### PR TITLE
Fix lints reported by clippy

### PR DESCRIPTION
**Pull request by wiktor-k**
The `no_mangle` caused a lint error:

```
error: attribute should be applied to a free function, impl method or static
  --> src/lib.rs:7:1
   |
7  |   #[no_mangle]
   |   ^^^^^^^^^^^^
8  | / extern "C" {
9  | |     fn launch_activate_socket(
10 | |         name: *const libc::c_char,
11 | |         fds: *mut *mut libc::c_int,
12 | |         cnt: *mut libc::size_t,
13 | |     ) -> libc::c_int;
14 | | }
   | |_- not a free function, impl method or static
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
```

### CODE REVIEW

**Comment by wiktor-k** [comment]
Thanks for the quick review :sweat_smile:  :wave:

**Comment by bbqsrc** [comment]
Always have time for a couple of crimes. :)

**Comment by bbqsrc** [comment]
@wiktor-k have invited you as a contributor, just tell me when you need me to publish something.

**Comment by wiktor-k** [comment]
> @wiktor-k have invited you as a contributor, just tell me when you need me to publish something.

Thanks a lot! Eventually yep, it'd be good to release it... but just a couple of small fixes here and there :sweat_smile:

**Pull request merged**
